// Code generated by "stringer -type=Lang"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[lblM3u8URL-0]
	_ = x[capCURL-1]
	_ = x[capError-2]
	_ = x[errInvalidM3U8-3]
	_ = x[errInvalidCURL-4]
	_ = x[lblSaveFolder-5]
	_ = x[btnChoose-6]
	_ = x[capSaveFolder-7]
	_ = x[lblSaveName-8]
	_ = x[lblSkipCode-9]
	_ = x[lblProxy-10]
	_ = x[lblBatch-11]
	_ = x[lblTemp-12]
	_ = x[capTemp-13]
	_ = x[lblInsecure-14]
	_ = x[lblKeepTS-15]
	_ = x[lblUseServerTime-16]
	_ = x[lblSkipMerge-17]
	_ = x[lblDebugLog-18]
	_ = x[lblSkipLog-19]
	_ = x[msgIdle-20]
	_ = x[btnMerge-21]
	_ = x[tipMerge-22]
	_ = x[btnStopMerge-23]
	_ = x[btnDownload-24]
	_ = x[tipDownload-25]
	_ = x[btnCancelDownload-26]
	_ = x[errBatchNum-27]
	_ = x[btnCurl-28]
	_ = x[btnOk-29]
	_ = x[btnCancel-30]
	_ = x[errDownload-31]
	_ = x[errDownloaded-32]
	_ = x[infDownloadDone-33]
	_ = x[infQueueDownloadDone-34]
	_ = x[errMerge-35]
	_ = x[errTSFolder-36]
	_ = x[errSaveFolder-37]
	_ = x[capInfo-38]
	_ = x[phtFolder-39]
	_ = x[phtSkipCode-40]
	_ = x[phtTemp-41]
	_ = x[phtProxy-42]
	_ = x[phtFileName-43]
	_ = x[btnFindIDMWindow-44]
	_ = x[txtIDMCancel-45]
	_ = x[tipIDMConfig-46]
	_ = x[txtIDMPromptTitle-47]
	_ = x[txtIDMPromptClass-48]
	_ = x[regIDMUrl-49]
	_ = x[regIDMName-50]
	_ = x[themeColor-51]
	_ = x[tabMain-52]
	_ = x[tabQueue-53]
	_ = x[btnAddQueueTxt-54]
	_ = x[btnRemoveQueue-55]
	_ = x[btnQueueTask-56]
	_ = x[btnQueueModify-57]
	_ = x[msgQueueDownloading-58]
	_ = x[numQueueHeight-59]
	_ = x[numQueueWidth-60]
	_ = x[stageIdle-61]
	_ = x[stageFetchM3U8-62]
	_ = x[stageM3U8Analysis-63]
	_ = x[stageDownloading-64]
	_ = x[stageMergeAnalysis-65]
	_ = x[stageMergeFiles-66]
}

const _Lang_name = "lblM3u8URLcapCURLcapErrorerrInvalidM3U8errInvalidCURLlblSaveFolderbtnChoosecapSaveFolderlblSaveNamelblSkipCodelblProxylblBatchlblTempcapTemplblInsecurelblKeepTSlblUseServerTimelblSkipMergelblDebugLoglblSkipLogmsgIdlebtnMergetipMergebtnStopMergebtnDownloadtipDownloadbtnCancelDownloaderrBatchNumbtnCurlbtnOkbtnCancelerrDownloaderrDownloadedinfDownloadDoneinfQueueDownloadDoneerrMergeerrTSFoldererrSaveFoldercapInfophtFolderphtSkipCodephtTempphtProxyphtFileNamebtnFindIDMWindowtxtIDMCanceltipIDMConfigtxtIDMPromptTitletxtIDMPromptClassregIDMUrlregIDMNamethemeColortabMaintabQueuebtnAddQueueTxtbtnRemoveQueuebtnQueueTaskbtnQueueModifymsgQueueDownloadingnumQueueHeightnumQueueWidthstageIdlestageFetchM3U8stageM3U8AnalysisstageDownloadingstageMergeAnalysisstageMergeFiles"

var _Lang_index = [...]uint16{0, 10, 17, 25, 39, 53, 66, 75, 88, 99, 110, 118, 126, 133, 140, 151, 160, 176, 188, 199, 209, 216, 224, 232, 244, 255, 266, 283, 294, 301, 306, 315, 326, 339, 354, 374, 382, 393, 406, 413, 422, 433, 440, 448, 459, 475, 487, 499, 516, 533, 542, 552, 562, 569, 577, 591, 605, 617, 631, 650, 664, 677, 686, 700, 717, 733, 751, 766}

func (i Lang) String() string {
	if i < 0 || i >= Lang(len(_Lang_index)-1) {
		return "Lang(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Lang_name[_Lang_index[i]:_Lang_index[i+1]]
}
