# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
            go-version: '1.24.4'
            cache-dependency-path: |
             ./go.sum
             ./go.sum
             
      - name: build
        run: |
          go mod tidy
          go build -o m3u8d_tk9ui.exe --ldflags="-s -w -H windowsgui"
          dir m3u8d_tk9ui.exe
          go build -o m3u8d_tk9ui_idm.exe -tags=idm --ldflags="-s -w -H windowsgui"
          dir m3u8d_tk9ui_idm.exe