# This is a basic workflow to help you get started with Actions

name: release-build-upload

# Controls when the workflow will run
on: 
  release:
    types: [ created ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-upload_windows-x64:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
            go-version: '1.24.4'
            cache-dependency-path: |
             ./go.sum
             ./go.sum
             
      - name: build
        run: |
          go mod tidy
          go build -o m3u8d_tk9ui.exe --ldflags="-s -w -H windowsgui"
          dir m3u8d_tk9ui.exe
      - name: upload release m3u8d_tk9ui
        uses: Guerra24/upload-to-release@v1
        with:
          name: m3u8d_tk9ui-${{ github.ref_name }}.exe
          path: m3u8d_tk9ui.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}